[tool.ruff]
line-length = 100
src = ["app"]
target-version = "py311"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.lint.per-file-ignores]
"app/config/__init__.py" = ["F403"]
"app/gui/__init__.py" = ["F401"]

[tool.mypy]
python_version = "3.11"
warn_unused_configs = true
ignore_missing_imports = true
warn_redundant_casts = true
warn_unused_ignores = true
strict_optional = true
show_error_codes = true
pretty = true
namespace_packages = true
mypy_path = ["app"]
disable_error_code = ["import-untyped"]

[[tool.mypy.overrides]]
module = "app.*"
check_untyped_defs = true
